## Reading Data From Different Sources

In [2]:
import pandas as pd
from io import StringIO

In [3]:
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title": "Team Lead", "title2": "Sr. Developer"}]}'
df = pd.read_json(StringIO(Data))

In [4]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title': 'Team Lead', 'title2': 'Sr. Developer'}"

In [5]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title":"Team Lead","title2":"Sr. Developer"}}}'

In [6]:
df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title":"Team Lead","title2":"Sr. Developer"}}]'

In [8]:
wine_data = pd.read_csv('WineQT.csv', header=None)

In [9]:
wine_data

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1,7.4,0.7,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
2,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.2,0.68,9.8,5,1
3,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.997,3.26,0.65,9.8,5,2
4,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.998,3.16,0.58,9.8,6,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1139,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1140,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1141,6.2,0.6,0.08,2.0,0.09,32.0,44.0,0.9949,3.45,0.58,10.5,5,1594
1142,5.9,0.55,0.1,2.2,0.062,39.0,51.0,0.9951200000000001,3.52,0.76,11.2,6,1595
1143,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.9954700000000001,3.57,0.71,10.2,5,1597

In [10]:
wine_data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
1,7.4,0.7,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
2,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.2,0.68,9.8,5,1
3,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.997,3.26,0.65,9.8,5,2
4,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.998,3.16,0.58,9.8,6,3

In [11]:
wine_data.tail()

,0,1,2,3,4,5,6,7,8,9,10,11,12
1139,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1140,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1141,6.2,0.6,0.08,2.0,0.09,32.0,44.0,0.9949,3.45,0.58,10.5,5,1594
1142,5.9,0.55,0.1,2.2,0.062,39.0,51.0,0.9951200000000001,3.52,0.76,11.2,6,1595
1143,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.9954700000000001,3.57,0.71,10.2,5,1597

In [12]:
wine_data.to_csv('wine.csv')

In [14]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.3-cp311-cp311-win_amd64.whl.metadata (3.4 kB)
Downloading lxml-6.1.3-cp311-cp311-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ----- ---------------------------------- 0.5/4.0 MB 153.9 kB/s eta 0:00:23
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ------- -------------------------------- 0.8/4.0 MB 122.0 kB/s eta 0:00:27
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ---------- ----------------------------- 1.0/4.0 MB 123.4 kB/s eta 0:00:25
   ------------- -------------------------- 1.3/4.0 MB 113.0 kB/s eta 0:00:25
   ------------- -------------------------- 1.3/4.0 MB 113.0 kB/s eta 0:00:25
   ------------- -------------------------- 1.3/4.0 MB 113.0 kB/s eta 0:00:25
   ------------- -------------------------- 1.3/4.0 MB 113.0 kB/s eta 0:00:25
   ------------- -------------------------- 1.3/4.0 MB 113.0 kB/s eta 0:00:25
   ------------- -------------------------- 1.3/4.0 MB 113.0 kB/s eta 0:00:25
   ------------- -------------------------- 1.3/4.0 MB 113.0 kB/s eta 0:00:25
   ------------- -------------------------- 1.3/4.0 MB 113.0 kB/s eta 0:00:25
   --------------- ------------------------ 1.6/4.0 MB 119.7 kB/s eta 0:00:21
   --------------- ------------------------ 1.6/4.0 MB 119.7 kB/s eta 0:00:21
   --------------- ------------------------ 1.6/4.0 MB 119.7 kB/s eta 0:00:21
   --------------- ------------------------ 1.6/4.0 MB 119.7 kB/s eta 0:00:21
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   ------------------ --------------------- 1.8/4.0 MB 132.8 kB/s eta 0:00:17
   -------------------- ------------------- 2.1/4.0 MB 127.4 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 127.4 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 127.4 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 127.4 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 127.4 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 127.4 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 127.4 kB/s eta 0:00:16
   -------------------- ------------------- 2.1/4.0 MB 127.4 kB/s eta 0:00:16
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   ----------------------- ---------------- 2.4/4.0 MB 130.7 kB/s eta 0:00:13
   -------------------------- ------------- 2.6/4.0 MB 125.7 kB/s eta 0:00:12
   -------------------------- ------------- 2.6/4.0 MB 125.7 kB/s eta 0:00:12
   -------------------------- ------------- 2.6/4.0 MB 125.7 kB/s eta 0:00:12
   -------------------------- ------------- 2.6/4.0 MB 125.7 kB/s eta 0:00:12
   -------------------------- ------------- 2.6/4.0 MB 125.7 kB/s eta 0:00:12
   -------------------------- ------------- 2.6/4.0 MB 125.7 kB/s eta 0:00:12
   -------------------------- ------------- 2.6/4.0 MB 125.7 kB/s eta 0:00:12
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ---------------------------- ----------- 2.9/4.0 MB 128.8 kB/s eta 0:00:09
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   ------------------------------- -------- 3.1/4.0 MB 125.5 kB/s eta 0:00:08
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 125.3 kB/s eta 0:00:05
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 124.6 kB/s eta 0:00:03
   ---------------------------------------  3.9/4.0 MB 125.7 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 125.7 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 125.7 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 126.4 kB/s  0:00:30
Installing collected packages: lxml
Successfully installed lxml-6.1.3

In [18]:
!pip install html5lib
!pip install beautifulsoup4

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in C:\Users\Shizi\anaconda3\envs\ml-journey\Lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in C:\Users\Shizi\anaconda3\envs\ml-journey\Lib\site-packages (from html5lib) (0.6.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Requirement already satisfied: beautifulsoup4 in C:\Users\Shizi\anaconda3\envs\ml-journey\Lib\site-packages (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\Shizi\anaconda3\envs\ml-journey\Lib\site-packages (from beautifulsoup4) (3.0.4)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\Shizi\anaconda3\envs\ml-journey\Lib\site-packages (from beautifulsoup4) (4.16.0)

In [19]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list"

html_info = pd.read_html(url)

In [20]:
html_info[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Nano Banc,Irvine,California,58590,Sunwest Bank,"September 25, 2026",10555
1,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
2,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
3,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
4,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
5,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
6,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
7,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
8,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
9,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
10,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
11,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
12,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
13,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
14,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
15,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
16,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
17,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
18,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
19,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
20,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
21,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
22,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
23,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
24,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529